name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust (cargo)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true


      - name: Install Selene
        run: |
          curl -L https://github.com/Kampfkarren/selene/releases/latest/download/selene-linux.tar.gz -o selene.tar.gz
          tar -xzf selene.tar.gz
          sudo mv selene /usr/local/bin/selene

      - name: Lint with Selene
        run: selene ./modules

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust (cargo)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install luau-lsp
        run: |
         curl -L https://github.com/JohnnyMorganz/luau-lsp/releases/latest/download/luau-lsp-linux.tar.gz -o luau-lsp.tar.gz
         tar -xzf luau-lsp.tar.gz
         sudo mv luau-lsp /usr/local/bin/luau-lsp

      - name: Run luau-lsp
        run: luau-lsp --version
