name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust (cargo)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Selene via Cargo
        run: cargo install selene

      - name: Lint with Selene
        run: selene ./modules

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install luau-lsp
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -L https://github.com/JohnnyMorganz/luau-lsp/releases/latest/download/luau-lsp-linux-x86_64.zip -o luau-lsp.zip
          unzip luau-lsp.zip
          sudo mv luau-lsp /usr/local/bin/luau-lsp

      - name: Run luau-lsp
        run: luau-lsp --version
